# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    cpus_per_task: 2
    # gpus_per_task: 0
    tasks_per_node: 1
    nodes: 1
    mem_gb: 8
    additional_parameters:
      mail-user: eisenaj@mit.edu
      # mail-type: END,FAIL,TIME_LIMIT
    array_parallelism: 800
    timeout_min: 15 # 24 hours by default