# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    cpus_per_task: 4
    gpus_per_task: 0
    tasks_per_node: 1
    nodes: 1
    mem_gb: 16
    partition: millerlab
    qos: millerlab
    additional_parameters:
      mail-user: eisenaj@mit.edu
      # mail-type: END,FAIL,TIME_LIMIT
    array_parallelism: 800
    timeout_min: 1440 # 24 hours by default
  job:
    chdir: true