defaults:
  - experiment: default

params:
  session: 'Mary-Anesthesia-20160912-02'
  # session: 'MrJones-Anesthesia-20160109-01'
  # shared_basis: false
  pca_dims: 12
  delay_p: 32
  delay_tau: 20
  standardize: true
  # standardize: false
  subsample: 3
  ltsa_n_components: 3
  n_neighbors_pct: 2.5
  window: 30 # s
  # start_times: [547.001, 1968.237] # Mary
  start_time: 547.001 # s
  


